#!/usr/bin/env bash
# Generates tools/cxx-runtime-rename.map, the symbols of V8's C++ runtime that
# tools/rename_cxx_runtime.sh renames in the Linux archives, so that a
# consumer binary can link libstdc++ next to v8go, even fully statically; and
# deps/linux_*/libv8go_cxxalias.a and botify_cxxalias_linux.go, the linker
# script and the --wrap flags that resolve the
# original names for source mode (-tags v8go_source).
#
# Chromium's libc++ keeps its library code in the private std::__Cr namespace,
# but libc++-cr.a and libc++abi-cr.a also define the C++ ABI layer under the
# names every C++ runtime uses: __cxa_*, __gxx_personality_v0,
# __dynamic_cast, std::exception and the other std:: exception classes, their
# typeinfo and vtables, the __cxxabiv1 typeinfo classes, std::terminate,
# operator new/delete... GCC's libstdc++/libsupc++ define the same names:
# a static link fails with "multiple definition", and a dynamic one lets
# Chromium's runtime interpose libstdc++'s (an exception thrown inside
# libstdc++.so then reaches std::terminate).
#
# The map covers every global symbol (strong, weak, hidden or not) defined by
# libc++-cr.a or libc++abi-cr.a outside Chromium's private namespaces (__Cr,
# __llvm_libc_cr), not only those a given GCC defines too: the set doesn't
# depend on the consumer's GCC version, and the g++ code's weak inline copies
# (bad_alloc's constructor, the typeinfo of std::bad_any_cast...) can't bind
# to Chromium's strong ones. Renaming a symbol no other runtime defines costs
# nothing. Each one gets the suffix .v8cr, a vendor suffix of the Itanium
# mangling: c++filt prints "typeinfo for std::exception [clone .v8cr]".
#
# Source mode compiles the v8go .cc files with cgo, so their objects reference
# the original names, which the renamed archives no longer define. The
# linker script, linked before the archives in source mode only
# (deps/linux_*/cgo.go), defines each original name the link references as an
# alias of the renamed one (PROVIDE), and EXTERN loads the archive members.
# GNU ld and lld read a file that is neither an object nor an archive as a
# linker script, also when -l finds it.
#
# Deterministic: it reads the archives of every deps/linux_* directory and
# maps a name already renamed back to its original, so it writes the same
# files before and after tools/rename_cxx_runtime.sh. Fails on a name outside
# the C++ ABI patterns below (an unwinder or libc symbol must never be renamed).
#
# Usage: tools/gen_cxx_runtime_rename_map.sh [root]
#   writes <root>/tools/cxx-runtime-rename.map and
#   <root>/deps/linux_*/libv8go_cxxalias.a and <root>/botify_cxxalias_linux.go
#   (default root: the repository).
# Reads ELF archives with llvm-nm (llvm-nm-NN...), else $NM (default nm).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
ROOT=${1:-.}

# llvm_tool <name> <fallback>: llvm-<name>, else the newest llvm-<name>-NN, else <fallback>.
llvm_tool() {
  local t
  for t in "llvm-$1" $(compgen -c "llvm-$1-" | grep -E "^llvm-$1-[0-9]+$" | sort -t- -k3 -rn); do
    if command -v "$t" >/dev/null; then echo "$t"; return; fi
  done
  echo "$2"
}
NM=$(llvm_tool nm "${NM:-nm}")
SUFFIX=.v8cr
# What a C++ runtime defines: mangled names, the Itanium C++ ABI entry points,
# libc++abi's helpers and the personality's DW.ref indirection, whose COMDAT
# group would otherwise be merged with g++'s and point every frame at one
# personality routine.
ABI='^(_Z|__cxa_|__gxx_personality_|__dynamic_cast$|__abort_message$|__clang_call_terminate$|DW\.ref\.__gxx_personality_)'

dirs=(deps/linux_*/)
dirs=("${dirs[@]%/}")
names=$(for d in "${dirs[@]}"; do
  for lib in "$d/libc++-cr.a" "$d/libc++abi-cr.a"; do
    [ -f "$lib" ] || { echo "$lib: missing" >&2; exit 1; }
    "$NM" -P --defined-only --extern-only "$lib" 2> >(grep -v ': no symbols$' >&2)
  done
done | awk 'NF >= 2 && $1 !~ /:$/ {print $1}' | sed "s/\\${SUFFIX}\$//" |
  grep -v -e '__Cr' -e '__llvm_libc_cr' | LC_ALL=C sort -u)

[ -n "$names" ] || { echo "no C++ runtime symbol found in ${dirs[*]}" >&2; exit 1; }
bad=$(grep -vE "$ABI" <<<"$names" || true)
if [ -n "$bad" ]; then
  echo "libc++-cr/libc++abi-cr define symbols outside the C++ ABI patterns; review them and $0:" >&2
  sed 's/^/  /' <<<"$bad" >&2
  exit 1
fi

# operator new/delete (new, new[], delete, delete[] and their variants).
newdel=$(grep -E '^_Z(nw|na|dl|da)' <<<"$names")
[ -n "$newdel" ] || { echo "no operator new/delete in libc++abi-cr" >&2; exit 1; }

mkdir -p "$ROOT/tools"
{
  echo "# Generated by tools/gen_cxx_runtime_rename_map.sh: V8's C++ runtime symbols and"
  echo "# their renamed form (llvm-objcopy --redefine-syms). Do not edit."
  awk -v s="$SUFFIX" '{print $1 " " $1 s}' <<<"$names"
} >"$ROOT/tools/cxx-runtime-rename.map"

for d in "${dirs[@]}"; do
  mkdir -p "$ROOT/$d"
  {
    echo "/* Generated by tools/gen_cxx_runtime_rename_map.sh. Do not edit."
    echo "   Linker script, source mode only (-tags v8go_source): the cgo-compiled"
    echo "   v8go objects reference V8's C++ runtime by its original names, defined"
    echo "   here as aliases of the renamed ones (tools/cxx-runtime-rename.map). */"
    awk -v s="$SUFFIX" '{print "EXTERN(\"" $1 s "\")"}' <<<"$names"
    awk -v s="$SUFFIX" '{print "PROVIDE(\"" $1 "\" = \"" $1 s "\");"}' <<<"$names"
    awk -v s="$SUFFIX" '{print "PROVIDE(\"__wrap_" $1 "\" = \"" $1 s "\");"}' <<<"$newdel"
  } >"$ROOT/$d/libv8go_cxxalias.a"
done

{
  echo "// Code generated by tools/gen_cxx_runtime_rename_map.sh. DO NOT EDIT."
  echo
  echo "//go:build v8go_source"
  echo
  echo "package v8go"
  echo
  echo "// Source mode: the v8go objects use V8's operator new/delete (Chromium's"
  echo "// libc++abi, renamed .v8cr in the archives), like the prebuilt bridge, even"
  echo "// when the link holds other strong ones (AddressSanitizer's for -tags"
  echo "// leakcheck, an allocator's): a PROVIDE alias can't override those, so"
  echo "// --wrap sends the references to __wrap_<name>, which"
  echo "// deps/linux_*/libv8go_cxxalias.a aliases to the renamed symbol."
  echo
  echo "// #cgo LDFLAGS:$(awk '{printf " -Wl,--wrap=%s", $1}' <<<"$newdel")"
  echo 'import "C"'
} >"$ROOT/botify_cxxalias_linux.go"
